version: "3.9"

services:

  backend:
    image: rwaj:latest
    container_name: rwaj_backend
    command: uvicorn src.app:app --ws=websockets --host 0.0.0.0 --port 8000 --log-level info
    ports:
      - "8000:8000"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - appnet
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: rwaj_db
    environment:
      POSTGRES_USER: zakaa_user
      POSTGRES_PASSWORD: zakaa_pass
      POSTGRES_DB: rwaj_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - appnet

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    volumes:
      - redis_data:/data
    deploy:
      replicas: 1
    networks:
      - appnet

  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit_server
    ports:
      - "7880:7880"  # WebRTC & REST
      - "7881:7881"  # WebRTC signaling (WS/WSS)
      - "7882:7882"  # optional metrics
    environment:
      LIVEKIT_KEYS: "API7vK4jxz9TSBX: Wx2OG9LvONllcw6DRVotM29dZ3s7aFkoUZvUJJKa7CL"  # format: key: secret
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - appnet

networks:
  appnet:
    driver: overlay

volumes:
  postgres_data:
  redis_data:
